<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://EuroToDollar.dauphine.fr" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://EuroToDollar.dauphine.fr" xmlns:intf="http://EuroToDollar.dauphine.fr" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="EuroToDollar">

   </wsdl:portType>

   <wsdl:binding name="EuroToDollarSoapBinding" type="impl:EuroToDollar">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="EuroToDollarService">

      <wsdl:port binding="impl:EuroToDollarSoapBinding" name="EuroToDollar">

         <wsdlsoap:address location="http://localhost:8080/BanqueService/services/EuroToDollar"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
